### ISSUE TITLE
JWT issue

### ISSUE THREAD

**Issue by harshan89stylesoft** [elibenjii/ecommerce-react#2]
throw new TypeError('JwtStrategy requires a secret or key')

**Comment by elibenjii** [comment]
I created the config.js file with a default secret. It should work now.
Next step: setup your mongo URI in config.js

**Comment by nicolasMartinez23** [comment]
Hello good afternoon.  I have a question, how is the purchase finalized and the order generated?  since in step 3 I don't see any confirmation button just the one from PayPal.

**Comment by elibenjii** [comment]
@nicolasMartinez23 Hi, you can easily add manually a gateway examples:
https://www.npmjs.com/package/react-stripe-checkout
https://www.npmjs.com/package/react-paypal-button-v2
