### ISSUE TITLE
Node api is not running

### ISSUE THREAD

**Issue by PlutusM** [elibenjii/ecommerce-react#4]
Used this code in terminal : node index.js & npm start

is running without errors. 

host/api response is like : 

Not Found
The requested URL was not found on this server.

Same with admin, its not running as well.

**Comment by elibenjii** [comment]
Hello,

To run the server type: node index.js
to run the client type: cd client && npm start

**Comment by PlutusM** [comment]
yah all ready used that, still its not working.

**Comment by NielsDom** [comment]
copy past the

**Comment by elibenjii** [comment]
show the server response please

**Comment by PlutusM** [comment]
Not Found
The requested URL was not found on this server.

Same with admin, its not running as well.

**Comment by elibenjii** [comment]
copy past all response from your server, it is not detailed enough
