### ISSUE TITLE
License: Can I use and extend it into my own commercial ecommerce?

### ISSUE THREAD

**Issue by aayushdutt** [elibenjii/ecommerce-react#5]
What are the license details of this project?

**Comment by elibenjii** [comment]
Hello, thanks for asking. You can use for commercial use for free, there is no licence.

**Comment by aayushdutt** [comment]
Thanks, @NielsDom. However, it will be much better if you specify the project under MIT License.

**Comment by elibenjii** [comment]
No problem, it is already stated MIT licence in package.json
